#!/bin/bash

# Internet Indicator for B860H v1/v2
# by Lutfa Ilham
# v3.0
# Edited by Nakumi

if [ "$(id -u)" != "0" ]; then
  echo "This script must be run as root" 1>&2
  exit 1
fi

SERVICE_NAME="Internet Indicator"

LED_ON_THRESHOLD=2500  # Ambang batas untuk mengaktifkan LED (25 KB/s)

function loop() {
  while true; do
    rx_traffic=$(cat /sys/class/net/eth0/statistics/rx_bytes)
    tx_traffic=$(cat /sys/class/net/eth0/statistics/tx_bytes)

    rx_diff=0
    tx_diff=0

    bledon -lan dis

    while true; do
      sleep 1
      new_rx_traffic=$(cat /sys/class/net/eth0/statistics/rx_bytes)
      new_tx_traffic=$(cat /sys/class/net/eth0/statistics/tx_bytes)

      rx_diff=$((new_rx_traffic - rx_traffic))
      tx_diff=$((new_tx_traffic - tx_traffic))

      if [ "$rx_diff" -gt $LED_ON_THRESHOLD ]; then
        bledon -lan on
      else
        bledon -lan dis
      fi

      if [ "$tx_diff" -gt $LED_ON_THRESHOLD ]; then
        bledon -lan off
      else
        bledon -lan dis
      fi

      rx_traffic=$new_rx_traffic
      tx_traffic=$new_tx_traffic
    done
  done
}

function start() {
  echo -e "Starting ${SERVICE_NAME} service ..."
  screen -AmdS internet-indicator "${0}" -l -l
}

function stop() {
  echo -e "Stopping ${SERVICE_NAME} service ..."
  kill $(screen -list | grep internet-indicator | awk -F '[.]' {'print $1'})
}

function usage() {
  cat <<EOF
Usage:
  -r  Run ${SERVICE_NAME} service
  -s  Stop ${SERVICE_NAME} service
EOF
}

case "${1}" in
  -l)
    loop
    ;;
  -r)
    start
    ;;
  -s)
    stop
    ;;
  *)
    usage
    ;;
esac
