#!/bin/bash

# B860H v1/v2 GPIO Wrapper
# by Lutfa Ilham
# v4.0
# Edited by Nakumi

if [ "$(id -u)" != "0" ]; then
  echo "This script must be run as root" 1>&2
  exit 1
fi

GPIO="/sys/class/gpio"

function dual_general() {
  pin_on="${2}"
  pin_off="${3}"
  echo "${pin_on}" > "${GPIO}/export"
  echo "${pin_off}" > "${GPIO}/export"
  echo out > "${GPIO}/gpio${pin_on}/direction"
  echo out > "${GPIO}/gpio${pin_off}/direction"
  case "${1}" in
    "on")
      echo 1 > "${GPIO}/gpio${pin_off}/value"
      echo 0 > "${GPIO}/gpio${pin_on}/value"
      ;;
    "off")
      echo 1 > "${GPIO}/gpio${pin_on}/value"
      echo 0 > "${GPIO}/gpio${pin_off}/value"
      ;;
    "warn")
      echo 1 > "${GPIO}/gpio${pin_on}/value"
      echo 1 > "${GPIO}/gpio${pin_off}/value"
      ;;
    "dis")
      echo 0 > "${GPIO}/gpio${pin_on}/value"
      echo 0 > "${GPIO}/gpio${pin_off}/value"
      ;;
  esac
}

function lan() {
  pin_on="476" # Hijau
  pin_off="474" # Merah
  dual_general "${1}" "${pin_on}" "${pin_off}"
}

function usage() {
  cat <<EOF
Usage:
  -power  [on, off, warn, dis]
  -lan    [on, off, warn, dis]
  -usb    [reset]
EOF
}

case "${1}" in
  -lan)
    lan "${2}"
    ;;
  *)
    usage
    ;;
esac
