#!/bin/bash

# B860H v1/v2 GPIO Wrapper
# by Lutfa Ilham
# v6.0
# Edited by Nakumi

if [ "$(id -u)" != "0" ]; then
  echo "This script must be run as root" 1>&2
  exit 1
fi

GPIO="/sys/class/gpio"

function dual_general() {
  pin_green="${2}"
  pin_red="${3}"
  echo "${pin_green}" > "${GPIO}/export"
  echo "${pin_red}" > "${GPIO}/export"
  echo out > "${GPIO}/gpio${pin_green}/direction"
  echo out > "${GPIO}/gpio${pin_red}/direction"
  case "${1}" in
    "green")
      echo 1 > "${GPIO}/gpio${pin_green}/value"
      ;;
    "red")
      echo 1 > "${GPIO}/gpio${pin_red}/value"
      ;;
    "warn")
      echo 1 > "${GPIO}/gpio${pin_green}/value"
      echo 1 > "${GPIO}/gpio${pin_red}/value"
      ;;
    "dis")
      echo 0 > "${GPIO}/gpio${pin_green}/value"
      echo 0 > "${GPIO}/gpio${pin_red}/value"
      ;;
  esac
}

function lan() {
  pin_red="476"
  pin_green="474"
  dual_general "${1}" "${pin_red}" "${pin_green}"
}

function usage() {
  cat <<EOF
Usage:
  -power  [green, red, warn, dis]
  -lan    [green, red, warn, dis]
  -usb    [reset]
EOF
}

case "${1}" in
  -lan)
    lan "${2}"
    ;;
  *)
    usage
    ;;
esac
